// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.0");

            modelBuilder.Entity("Domain.WeatherForecast", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .HasColumnType("TEXT");

                    b.Property<int>("TemperatureC")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("WeatherForecasts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2019, 11, 6, 9, 2, 32, 21, DateTimeKind.Local).AddTicks(4800),
                            Summary = "Frigid",
                            TemperatureC = -7
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2019, 11, 7, 9, 2, 32, 41, DateTimeKind.Local).AddTicks(7230),
                            Summary = "Human",
                            TemperatureC = 37
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2019, 11, 8, 9, 2, 32, 41, DateTimeKind.Local).AddTicks(7290),
                            Summary = "Perfection",
                            TemperatureC = 23
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
